### ISSUE TITLE
Why does `get_or_insert` return `Option`?

### ISSUE THREAD

**Issue by nazar-pc** [koute/schnellru#7]
Looking at `get_or_insert` method signature I do not understand what does it mean if it returns `None`.

If key exists I should get a mutable reference to existing value, if not then new value will be inserted and I should still get a mutable reference to newly inserted value. When why would I ever get `None` back?

**Comment by koute** [comment]
> When why would I ever get `None` back?

The new value might not have been inserted due to the limiter (e.g. the new element is 100 bytes and the limiter is set to limit the map to a maximum of 60 bytes in total), or the memory allocation failed.

**Comment by nazar-pc** [comment]
I see. Allocation is something I don't expect to receive an `Option` for generally, but size limiter makes sense. Maybe worth updating method documentation a bit since it wasn't immediately obvious.

Appreciate for quick response!
